
spring:
  application:
    name: bluemoon-edtech
  datasource:
    url: jdbc:postgresql://localhost:5432/edtech_db
    username: postgres
    password: NewStrongPassword123
  jpa:
    hibernate:
      ddl-auto: update     # <-- this tells Hibernate to create/update tables
    show-sql: true         # <-- prints SQL to logs
    properties:
      hibernate:
        format_sql: true


jwt:
  secret: manchester_is_always_blue_will_be_blue_and_forever
  expiration-ms: 86400000 # 1 day in ms




server:
  port: 8081
